FROM ruby:2.4.1

ENV LANG C.UTF-8

RUN apt-get update -qq && \
 apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \
  libfontconfig1 && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone -b 0.3 https://github.com/kter/workspace

WORKDIR /app/workspace/wallet

RUN bundle config build.nokogiri --use-system-libraries && bundle install --quiet

CMD bundle exec rails s -p 3000 -b 0.0.0.0
